version: "3"
services:
  #PHP Service
  php:
    container_name: php
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - /var/www/html/vendor/
    networks:
      - app-network
    depends_on:
      - db

  #MySQL Service
  db:
    container_name: db
    image: mariadb
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yii2basic
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Bangkok
    networks:
      - app-network
  #PMA
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "9831:80"
    links:
      - db:db
    networks:
      - app-network
    depends_on:
      - db

# #Docker Networks
networks:
  app-network:
    driver: bridge
